# Practice Session 01: Data preparation

Author: <font color="blue">Bo-Yu Chen</font>

E-mail: <font color="blue">8011chen@gmail.com</font>

AI used: <font color="blue">Claude Sonnet5.5 To help me double check.</font>

Date: <font color="blue">30/09/2026</font>

In [1]:
# LEAVE AS-IS

# Pandas library
import pandas as pd

# Show more rows in the output
pd.set_option("display.max_rows", 100)

# 1. Load dataset

In [2]:
# LEAVE AS-IS

input_dataset = pd.read_csv("listings.csv.gz", compression="gzip")

# 2. Column types and null values <font color="blue">[10%]</font>

In [3]:
# LEAVE AS-IS

input_dataset.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.529300e+04,1.529300e+04,0.0,1.529300e+04,1.520600e+04,0.0,15206.000000,15206.000000,15206.000000,15206.000000,...,11744.000000,11744.000000,11744.000000,11744.000000,0.0,15293.000000,15293.000000,15293.000000,15293.000000,11745.000000
mean,7.081310e+17,2.026062e+13,NaN,1.029976e+16,1.470058e+18,NaN,8.643628,5.134618,7.851309,4.990464,...,4.726335,4.722973,4.766025,4.465703,NaN,73.839992,65.734454,7.860394,0.124371,1.555447
std,6.550632e+17,0.000000e+00,NaN,1.316853e+17,2.707029e+16,NaN,4.120495,3.482615,4.282838,3.549561,...,0.463476,0.478455,0.362881,0.542243,NaN,146.257623,145.422963,30.752961,0.796254,2.318884
min,1.867400e+04,2.026062e+13,NaN,1.070400e+04,1.462507e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.223180e+07,2.026062e+13,NaN,9.469830e+06,1.462659e+18,NaN,6.000000,2.000000,4.000000,1.000000,...,4.670000,4.670000,4.700000,4.330000,NaN,2.000000,1.000000,0.000000,0.000000,0.220000
50%,8.005535e+17,2.026062e+13,NaN,9.633738e+07,1.465487e+18,NaN,9.000000,5.000000,8.000000,5.000000,...,4.850000,4.860000,4.850000,4.570000,NaN,10.000000,5.000000,0.000000,0.000000,0.950000
75%,1.344730e+18,2.026062e+13,NaN,3.463675e+08,1.469532e+18,NaN,12.000000,8.000000,11.000000,8.000000,...,5.000000,5.000000,4.990000,4.770000,NaN,43.000000,31.000000,1.000000,0.000000,2.350000
max,1.714532e+18,2.026062e+13,NaN,1.713762e+18,1.714078e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,588.000000,588.000000,205.000000,12.000000,100.580000

<font size="+1" color="blue">**Create function "describe_dataframe".** It must create and display a dataframe containing one row per column, and with the following fields: name of the column ("name"), type ("data_type"), number of non-null values ("count_not_null"), and number of distinct elements ("count_distinct").</font>

In [4]:
def describe_dataframe(df):
    # YOUR CODE HERE
    input_columns = pd.DataFrame(columns=["name", "data_type", "count_not_null", "count_distinct"])
    for column in df.columns:
        input_columns.loc[len(input_columns)] = [column, df[column].dtype, df[column].notnull().sum(), df[column].nunique()]
    
    
    
    return input_columns

input_columns = describe_dataframe(input_dataset)
display(input_columns)

,name,data_type,count_not_null,count_distinct
0,id,int64,15293,15293
1,listing_url,str,15293,15293
2,scrape_id,int64,15293,1
3,last_scraped,str,15293,4
4,source,str,15293,2
5,name,str,15293,14694
6,description,str,14644,11815
7,neighborhood_overview,float64,0,0
8,picture_url,str,15293,15145
9,host_id,int64,15293,4595
10,host_url,str,15293,4595
11,host_profile_id,float64,15206,4553
12,host_profile_url,str,15212,4555
13,host_name,str,15206,2510
14,host_since,float64,0,0
15,hosts_time_as_user_years,float64,15206,18
16,hosts_time_as_user_months,float64,15206,12
17,hosts_time_as_host_years,float64,15206,16
18,hosts_time_as_host_months,float64,15206,12
19,host_location,str,12195,321
20,host_about,str,10434,2406
21,host_response_time,float64,0,0
22,host_response_rate,float64,0,0
23,host_acceptance_rate,float64,0,0
24,host_is_superhost,str,15206,2
25,host_thumbnail_url,float64,0,0
26,host_picture_url,str,15206,4468
27,host_neighbourhood,float64,0,0
28,host_listings_count,float64,15206,97
29,host_total_listings_count,float64,0,0
30,host_verifications,float64,0,0
31,host_has_profile_pic,str,15206,2
32,host_identity_verified,str,15206,2
33,neighbourhood,float64,0,0
34,neighbourhood_cleansed,str,15293,69
35,neighbourhood_group_cleansed,str,15293,10
36,latitude,float64,15293,8772
37,longitude,float64,15293,9484
38,property_type,str,15293,50
39,room_type,str,15293,4
40,accommodates,int64,15293,16
41,bathrooms,float64,11728,21
42,bathrooms_text,str,15280,37
43,bedrooms,float64,12731,23
44,beds,float64,12846,32
45,amenities,str,15293,13161
46,price,str,13355,6365
47,price_quote_checkin_date,str,13662,293
48,price_quote_checkout_date,str,13662,332
49,price_quote_total_price,float64,13355,6134
50,price_quote_price_per_night,float64,13355,6365
51,price_quote_raw,str,13662,12192
52,minimum_nights,float64,15292,65
53,maximum_nights,float64,15292,183
54,minimum_minimum_nights,float64,15292,65
55,maximum_minimum_nights,float64,15292,73
56,minimum_maximum_nights,float64,15292,185
57,maximum_maximum_nights,float64,15292,183
58,minimum_nights_avg_ntm,float64,15293,389
59,maximum_nights_avg_ntm,float64,15293,1125
60,calendar_updated,float64,0,0
61,has_availability,str,15219,2
62,availability_30,int64,15293,31
63,availability_60,int64,15293,61
64,availability_90,int64,15293,91
65,availability_365,int64,15293,366
66,calendar_last_scraped,str,15293,4
67,number_of_reviews,int64,15293,688
68,number_of_reviews_ltm,int64,15293,191
69,number_of_reviews_l30d,int64,15293,37
70,availability_eoy,int64,15293,192
71,number_of_reviews_ly,int64,15293,180
72,estimated_occupancy_l365d,int64,15293,88
73,estimated_revenue_l365d,float64,13355,6977
74,first_review,str,11745,3836
75,last_review,str,11745,1594
76,review_scores_rating,float64,11745,157
77,review_scores_accuracy,float64,11744,153
78,review_scores_cleanliness,float64,11744,162
79,review_scores_checkin,float64,11744,142
80,review_scores_communication,float64,11744,139
81,review_scores_location,float64,11744,134
82,review_scores_value,float64,11744,173
83,license,str,12250,10371
84,instant_bookable,float64,0,0
85,calculated_host_listings_count,int64,15293,61
86,calculated_host_listings_count_entire_homes,int64,15293,56
87,calculated_host_listings_count_private_rooms,int64,15293,32
88,calculated_host_listings_count_shared_rooms,int64,15293,9
89,reviews_per_month,float64,11745,786

# 3. Remove empty columns <font color="blue">[10%]</font>

<font size="+1" color="blue">**Create function "drop_empty_columns"**. It should iterate through the columns in the original dataset, and return a new dataframe without the empty columns in the original one.</font>

In [5]:
def drop_empty_columns(df):
    df_without_empty_columns = pd.DataFrame()
    for column in df.columns:
        if df[column].notnull().sum()!=0:
            df_without_empty_columns[column] = df[column].values
    
    # YOUR CODE HERE
    return df_without_empty_columns
    
df1 = drop_empty_columns(input_dataset)

display(describe_dataframe(df1))

,name,data_type,count_not_null,count_distinct
0,id,int64,15293,15293
1,listing_url,str,15293,15293
2,scrape_id,int64,15293,1
3,last_scraped,str,15293,4
4,source,str,15293,2
5,name,str,15293,14694
6,description,str,14644,11815
7,picture_url,str,15293,15145
8,host_id,int64,15293,4595
9,host_url,str,15293,4595
10,host_profile_id,float64,15206,4553
11,host_profile_url,str,15212,4555
12,host_name,str,15206,2510
13,hosts_time_as_user_years,float64,15206,18
14,hosts_time_as_user_months,float64,15206,12
15,hosts_time_as_host_years,float64,15206,16
16,hosts_time_as_host_months,float64,15206,12
17,host_location,str,12195,321
18,host_about,str,10434,2406
19,host_is_superhost,str,15206,2
20,host_picture_url,str,15206,4468
21,host_listings_count,float64,15206,97
22,host_has_profile_pic,str,15206,2
23,host_identity_verified,str,15206,2
24,neighbourhood_cleansed,str,15293,69
25,neighbourhood_group_cleansed,str,15293,10
26,latitude,float64,15293,8772
27,longitude,float64,15293,9484
28,property_type,str,15293,50
29,room_type,str,15293,4
30,accommodates,int64,15293,16
31,bathrooms,float64,11728,21
32,bathrooms_text,str,15280,37
33,bedrooms,float64,12731,23
34,beds,float64,12846,32
35,amenities,str,15293,13161
36,price,str,13355,6365
37,price_quote_checkin_date,str,13662,293
38,price_quote_checkout_date,str,13662,332
39,price_quote_total_price,float64,13355,6134
40,price_quote_price_per_night,float64,13355,6365
41,price_quote_raw,str,13662,12192
42,minimum_nights,float64,15292,65
43,maximum_nights,float64,15292,183
44,minimum_minimum_nights,float64,15292,65
45,maximum_minimum_nights,float64,15292,73
46,minimum_maximum_nights,float64,15292,185
47,maximum_maximum_nights,float64,15292,183
48,minimum_nights_avg_ntm,float64,15293,389
49,maximum_nights_avg_ntm,float64,15293,1125
50,has_availability,str,15219,2
51,availability_30,int64,15293,31
52,availability_60,int64,15293,61
53,availability_90,int64,15293,91
54,availability_365,int64,15293,366
55,calendar_last_scraped,str,15293,4
56,number_of_reviews,int64,15293,688
57,number_of_reviews_ltm,int64,15293,191
58,number_of_reviews_l30d,int64,15293,37
59,availability_eoy,int64,15293,192
60,number_of_reviews_ly,int64,15293,180
61,estimated_occupancy_l365d,int64,15293,88
62,estimated_revenue_l365d,float64,13355,6977
63,first_review,str,11745,3836
64,last_review,str,11745,1594
65,review_scores_rating,float64,11745,157
66,review_scores_accuracy,float64,11744,153
67,review_scores_cleanliness,float64,11744,162
68,review_scores_checkin,float64,11744,142
69,review_scores_communication,float64,11744,139
70,review_scores_location,float64,11744,134
71,review_scores_value,float64,11744,173
72,license,str,12250,10371
73,calculated_host_listings_count,int64,15293,61
74,calculated_host_listings_count_entire_homes,int64,15293,56
75,calculated_host_listings_count_private_rooms,int64,15293,32
76,calculated_host_listings_count_shared_rooms,int64,15293,9
77,reviews_per_month,float64,11745,786

# 4. Handle missing information about hosts <font color="blue">[30%]</font>

<font size="+1" color="blue">**Create function "drop_empty_hosts_v1"**. It should remove rows containing a null "host_profile_id" and indicate how many rows were removed (absolute and percentage).</font>

In [6]:
def drop_empty_hosts_v1(df):
    
    # YOUR CODE HERE
    df_clean = df.copy(deep=True)
    df_clean = df_clean.dropna(axis=0, subset=["host_profile_id"])
    
    print(f"A total of {len(df)-len(df_clean)} rows are removed.")
    print(f"A total of {(len(df)-len(df_clean)) / len(df) * 100}% of rows are removed.")
    
    return df_clean
    
df2 = drop_empty_hosts_v1(df1)

display(describe_dataframe(df2))

A total of 87 rows are removed.
A total of 0.5688877264107762% of rows are removed.

,name,data_type,count_not_null,count_distinct
0,id,int64,15206,15206
1,listing_url,str,15206,15206
2,scrape_id,int64,15206,1
3,last_scraped,str,15206,4
4,source,str,15206,2
5,name,str,15206,14637
6,description,str,14641,11812
7,picture_url,str,15206,15058
8,host_id,int64,15206,4553
9,host_url,str,15206,4553
10,host_profile_id,float64,15206,4553
11,host_profile_url,str,15203,4553
12,host_name,str,15206,2510
13,hosts_time_as_user_years,float64,15206,18
14,hosts_time_as_user_months,float64,15206,12
15,hosts_time_as_host_years,float64,15206,16
16,hosts_time_as_host_months,float64,15206,12
17,host_location,str,12195,321
18,host_about,str,10434,2406
19,host_is_superhost,str,15206,2
20,host_picture_url,str,15206,4468
21,host_listings_count,float64,15206,97
22,host_has_profile_pic,str,15206,2
23,host_identity_verified,str,15206,2
24,neighbourhood_cleansed,str,15206,69
25,neighbourhood_group_cleansed,str,15206,10
26,latitude,float64,15206,8758
27,longitude,float64,15206,9464
28,property_type,str,15206,50
29,room_type,str,15206,4
30,accommodates,int64,15206,16
31,bathrooms,float64,11728,21
32,bathrooms_text,str,15193,37
33,bedrooms,float64,12731,23
34,beds,float64,12846,32
35,amenities,str,15206,13121
36,price,str,13280,6325
37,price_quote_checkin_date,str,13586,293
38,price_quote_checkout_date,str,13586,332
39,price_quote_total_price,float64,13280,6092
40,price_quote_price_per_night,float64,13280,6325
41,price_quote_raw,str,13586,12137
42,minimum_nights,float64,15205,65
43,maximum_nights,float64,15205,183
44,minimum_minimum_nights,float64,15205,65
45,maximum_minimum_nights,float64,15205,73
46,minimum_maximum_nights,float64,15205,185
47,maximum_maximum_nights,float64,15205,183
48,minimum_nights_avg_ntm,float64,15206,389
49,maximum_nights_avg_ntm,float64,15206,1077
50,has_availability,str,15132,2
51,availability_30,int64,15206,31
52,availability_60,int64,15206,61
53,availability_90,int64,15206,91
54,availability_365,int64,15206,366
55,calendar_last_scraped,str,15206,4
56,number_of_reviews,int64,15206,688
57,number_of_reviews_ltm,int64,15206,191
58,number_of_reviews_l30d,int64,15206,37
59,availability_eoy,int64,15206,192
60,number_of_reviews_ly,int64,15206,180
61,estimated_occupancy_l365d,int64,15206,88
62,estimated_revenue_l365d,float64,13280,6939
63,first_review,str,11681,3834
64,last_review,str,11681,1589
65,review_scores_rating,float64,11681,157
66,review_scores_accuracy,float64,11680,153
67,review_scores_cleanliness,float64,11680,162
68,review_scores_checkin,float64,11680,142
69,review_scores_communication,float64,11680,139
70,review_scores_location,float64,11680,134
71,review_scores_value,float64,11680,173
72,license,str,12250,10371
73,calculated_host_listings_count,int64,15206,61
74,calculated_host_listings_count_entire_homes,int64,15206,56
75,calculated_host_listings_count_private_rooms,int64,15206,32
76,calculated_host_listings_count_shared_rooms,int64,15206,9
77,reviews_per_month,float64,11681,782

In [7]:
drop_row_columns = []
fill_row_columns = []

for column in df1.columns:
    if column.startswith("host_"):
        print(f"for column {column} there is {df1[column].isna().sum()} null values, which is {df1[column].isna().sum() / df1[column].shape[0] * 100}% of the values.")
        if df1[column].isna().sum() / df1[column].shape[0] * 100 >= 1:
            fill_row_columns.append(column)
        else:
            drop_row_columns.append(column)
            
print(f"fill rows in {fill_row_columns}")
print(f"drop rows in {drop_row_columns}")

for column host_id there is 0 null values, which is 0.0% of the values.
for column host_url there is 0 null values, which is 0.0% of the values.
for column host_profile_id there is 87 null values, which is 0.5688877264107762% of the values.
for column host_profile_url there is 81 null values, which is 0.5296540901065847% of the values.
for column host_name there is 87 null values, which is 0.5688877264107762% of the values.
for column host_location there is 3098 null values, which is 20.257634211730856% of the values.
for column host_about there is 4859 null values, which is 31.77270646701105% of the values.
for column host_is_superhost there is 87 null values, which is 0.5688877264107762% of the values.
for column host_picture_url there is 87 null values, which is 0.5688877264107762% of the values.
for column host_listings_count there is 87 null values, which is 0.5688877264107762% of the values.
for column host_has_profile_pic there is 87 null values, which is 0.5688877264107762% of the values.
for column host_identity_verified there is 87 null values, which is 0.5688877264107762% of the values.
fill rows in ['host_location', 'host_about']
drop rows in ['host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_is_superhost', 'host_picture_url', 'host_listings_count', 'host_has_profile_pic', 'host_identity_verified']

<font size="+1" color="blue">**Write your strategy for handling null values in host-related columns**. Indicate in which cases you will drop the entire row, and in which cases you will replace by a default value.</font>

**Answer:** the strategy for handling nulls in host-related information will be as follows.

First, drop entire rows for nulls in these columns:
* ('host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_is_superhost', 'host_picture_url', 'host_listings_count', 'host_has_profile_pic', 'host_identity_verified')

Second, replace with a default value the nulls in these columns:
* ('host_location')
            
Third, replace with a zero or empty string the nulls in these columns:
* ('host_about')

<font size="+1" color="blue">**Write a function that gives you the modal value for a column**. You will use to generate a default value.</font>

In [8]:
def determine_modal_value(df, column):
    
    # YOUR CODE HERE
    modal_value = df.mode(axis=0)[column][0]
    
    return modal_value

<font size="+1" color="blue">**Write a function drop_empty_hosts_v2**. That does the same as its v1 plus applying your strategy for handling missing information about hosts.</font>

In [9]:
def drop_empty_hosts_v2(df):
    modal_location = determine_modal_value(df, "host_location")
    print(f"Modal location: {modal_location}")
  
    # YOUR CODE HERE
    df_clean = df.copy(deep=True)
    df_clean = df_clean.dropna(axis=0, subset=['host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_is_superhost', 'host_picture_url', 'host_listings_count', 'host_has_profile_pic', 'host_identity_verified'])
    
    # for host_location
    df_clean["host_location"] = df_clean["host_location"].fillna(modal_location)
    
    # for host_about
    df_clean["host_about"] = df_clean["host_about"].fillna("")
    
    print(f"A total of {len(df)-len(df_clean)} rows are removed.")
    print(f"A total of {(len(df)-len(df_clean)) / len(df) * 100}% of rows are removed.")
    
    return df_clean
    
df2 = drop_empty_hosts_v2(df1)

display(describe_dataframe(df2))

Modal location: Barcelona, Spain
A total of 90 rows are removed.
A total of 0.5885045445628719% of rows are removed.

,name,data_type,count_not_null,count_distinct
0,id,int64,15203,15203
1,listing_url,str,15203,15203
2,scrape_id,int64,15203,1
3,last_scraped,str,15203,4
4,source,str,15203,2
5,name,str,15203,14634
6,description,str,14641,11812
7,picture_url,str,15203,15055
8,host_id,int64,15203,4553
9,host_url,str,15203,4553
10,host_profile_id,float64,15203,4553
11,host_profile_url,str,15203,4553
12,host_name,str,15203,2510
13,hosts_time_as_user_years,float64,15203,18
14,hosts_time_as_user_months,float64,15203,12
15,hosts_time_as_host_years,float64,15203,16
16,hosts_time_as_host_months,float64,15203,12
17,host_location,str,15203,321
18,host_about,str,15203,2407
19,host_is_superhost,str,15203,2
20,host_picture_url,str,15203,4468
21,host_listings_count,float64,15203,97
22,host_has_profile_pic,str,15203,2
23,host_identity_verified,str,15203,2
24,neighbourhood_cleansed,str,15203,69
25,neighbourhood_group_cleansed,str,15203,10
26,latitude,float64,15203,8758
27,longitude,float64,15203,9464
28,property_type,str,15203,50
29,room_type,str,15203,4
30,accommodates,int64,15203,16
31,bathrooms,float64,11728,21
32,bathrooms_text,str,15190,37
33,bedrooms,float64,12731,23
34,beds,float64,12846,32
35,amenities,str,15203,13120
36,price,str,13277,6323
37,price_quote_checkin_date,str,13583,293
38,price_quote_checkout_date,str,13583,332
39,price_quote_total_price,float64,13277,6090
40,price_quote_price_per_night,float64,13277,6323
41,price_quote_raw,str,13583,12135
42,minimum_nights,float64,15202,65
43,maximum_nights,float64,15202,183
44,minimum_minimum_nights,float64,15202,65
45,maximum_minimum_nights,float64,15202,73
46,minimum_maximum_nights,float64,15202,185
47,maximum_maximum_nights,float64,15202,183
48,minimum_nights_avg_ntm,float64,15203,389
49,maximum_nights_avg_ntm,float64,15203,1074
50,has_availability,str,15129,1
51,availability_30,int64,15203,31
52,availability_60,int64,15203,61
53,availability_90,int64,15203,91
54,availability_365,int64,15203,366
55,calendar_last_scraped,str,15203,4
56,number_of_reviews,int64,15203,688
57,number_of_reviews_ltm,int64,15203,191
58,number_of_reviews_l30d,int64,15203,37
59,availability_eoy,int64,15203,192
60,number_of_reviews_ly,int64,15203,180
61,estimated_occupancy_l365d,int64,15203,88
62,estimated_revenue_l365d,float64,13277,6938
63,first_review,str,11680,3834
64,last_review,str,11680,1589
65,review_scores_rating,float64,11680,157
66,review_scores_accuracy,float64,11679,153
67,review_scores_cleanliness,float64,11679,162
68,review_scores_checkin,float64,11679,142
69,review_scores_communication,float64,11679,139
70,review_scores_location,float64,11679,134
71,review_scores_value,float64,11679,173
72,license,str,12250,10371
73,calculated_host_listings_count,int64,15203,61
74,calculated_host_listings_count_entire_homes,int64,15203,56
75,calculated_host_listings_count_private_rooms,int64,15203,32
76,calculated_host_listings_count_shared_rooms,int64,15203,9
77,reviews_per_month,float64,11680,782

In [10]:
# LEAVE AS-IS

# Check that all the host columns have the same number of values 
# as the id column
def check_host_columns(df):
    id_not_null = df["id"].notnull().sum()
    
    for col in df.columns:
        if col.startswith("host_"):
            null_values_in_column = df[col].notnull().sum()
            if null_values_in_column != id_not_null:
                print(f"Problem in column {col}, it has {null_values_in_column}")
                return False
            
    return True

check_host_columns(df2)

True

In [11]:
# LEAVE AS-IS

# Print table with columns containing null values
def null_value_counts(df):
    count_null_values = df.isnull().sum()
    columns_with_null_values = count_null_values[count_null_values > 0].reset_index()
    columns_with_null_values.columns = ["column", "null_count"]
    return columns_with_null_values
    
display(null_value_counts(df2))

                         column  null_count
0                   description         562
1                     bathrooms        3475
2                bathrooms_text          13
3                      bedrooms        2472
4                          beds        2357
5                         price        1926
6      price_quote_checkin_date        1620
7     price_quote_checkout_date        1620
8       price_quote_total_price        1926
9   price_quote_price_per_night        1926
10              price_quote_raw        1620
11               minimum_nights           1
12               maximum_nights           1
13       minimum_minimum_nights           1
14       maximum_minimum_nights           1
15       minimum_maximum_nights           1
16       maximum_maximum_nights           1
17             has_availability          74
18      estimated_revenue_l365d        1926
19                 first_review        3523
20                  last_review        3523
21         review_scores_rating        3523
22       review_scores_accuracy        3524
23    review_scores_cleanliness        3524
24        review_scores_checkin        3524
25  review_scores_communication        3524
26       review_scores_location        3524
27          review_scores_value        3524
28                      license        2953
29            reviews_per_month        3523

# 5. Handle null values in number of bathrooms and bedrooms <font color="blue">[30%]</font>

<font size="+1" color="blue">**Include whatever code you need to decide your null-handling strategy for bathrooms and bedrooms**. Cross-tabulating the data is helpful, we have included one example of this.</font>

In [12]:
# Print distribution of the `bathrooms` column:
display(df2["bathrooms"].value_counts().sort_index())

# Print cross-distributions of the
# `bathrooms` and `bathrooms_text` columns.
# By default pd.crosstab drops null values, but we want to see them.

# AI Generated, edited (Claude Sonnet 5)
bathroom_crosstab = pd.crosstab(
    df2["bathrooms"].fillna("(null)"),
    df2["bathrooms_text"].fillna("(null)")
)
display(bathroom_crosstab)

# Continue with whatever you need to justify your decisions below
# YOUR CODE HERE
display(df2["beds"].value_counts().sort_index())

display(df2["bedrooms"].value_counts().sort_index())

bedroom_crosstab = pd.crosstab(
    df2["beds"].fillna("(null)"),
    df2["bedrooms"].fillna("(null)")
)
display(bedroom_crosstab)

bathrooms
0.5       64
1.0     7053
1.5      540
2.0     3260
2.5      141
3.0      291
3.5       27
4.0      164
4.5        9
5.0       57
5.5        5
6.0       45
7.0        6
8.0       40
9.0        4
10.0      10
11.0       3
12.0       6
13.0       1
14.0       1
16.0       1
Name: count, dtype: int64

bathrooms_text,(null),0 baths,0 shared baths,1 bath,1 private bath,1 shared bath,1.5 baths,1.5 shared baths,10 baths,11 baths,...,5.5 baths,6 baths,7 baths,7 shared baths,8 baths,8 shared baths,9 baths,Half-bath,Private half-bath,Shared half-bath
bathrooms,,,,,,,,,,,,,,,,,,,,,
0.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,21,7,36
1.0,0,1,0,5310,783,959,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1.5,1,0,0,0,0,0,410,129,0,0,...,0,0,0,0,0,0,0,0,0,0
2.0,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2.5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4.0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.5,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
6.0,0,0,0,0,0,0,0,0,0,0,...,0,45,0,0,0,0,0,0,0,0
7.0,0,0,0,0,0,0,0,0,0,0,...,0,0,5,1,0,0,0,0,0,0
8.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,22,18,0,0,0,0
9.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,4,0,0,0
10.0,0,0,0,0,0,0,0,0,10,0,...,0,0,0,0,0,0,0,0,0,0
11.0,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
12.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
(null),9,506,213,1006,314,614,129,86,1,1,...,0,5,2,0,3,0,1,4,2,8

beds
1.0      4151
2.0      2829
3.0      2478
4.0      1618
5.0       747
6.0       440
7.0       207
8.0        97
9.0        57
10.0       43
11.0       18
12.0       44
13.0       14
14.0       10
15.0       20
16.0       18
17.0        5
18.0        9
20.0       15
21.0        2
22.0        4
23.0        1
24.0        5
25.0        3
26.0        2
30.0        2
31.0        1
32.0        1
33.0        2
35.0        1
37.0        1
127.0       1
Name: count, dtype: int64

bedrooms
0.0        4
1.0     4757
2.0     4241
3.0     2502
4.0      786
5.0      167
6.0       97
7.0       20
8.0       47
9.0       31
10.0      20
11.0      10
12.0      26
13.0       1
14.0       2
15.0       8
16.0       2
18.0       1
19.0       1
20.0       4
24.0       2
26.0       1
29.0       1
Name: count, dtype: int64

bedrooms,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,14.0,15.0,16.0,18.0,19.0,20.0,24.0,26.0,29.0,(null)
beds,,,,,,,,,,,,,,,,,,,,,
1.0,0,2802,72,19,9,9,1,4,9,3,...,0,0,0,0,1,0,0,0,1,1220
2.0,0,1046,1611,16,2,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,153
3.0,0,224,1438,781,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,32
4.0,0,62,527,766,247,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,14
5.0,0,9,111,431,149,39,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
6.0,0,12,8,228,151,24,12,0,0,0,...,0,0,0,0,0,0,0,0,0,5
7.0,0,3,4,57,98,33,8,1,0,0,...,0,0,0,0,0,0,0,0,0,3
8.0,0,11,2,5,36,22,10,1,7,2,...,0,0,0,0,0,0,0,0,0,0
9.0,0,0,1,3,11,13,22,0,1,6,...,0,0,0,0,0,0,0,0,0,0
10.0,0,4,0,1,11,10,12,2,0,2,...,0,0,0,0,0,0,0,0,0,0
11.0,0,1,0,0,0,2,6,2,3,2,...,0,0,0,0,0,0,0,0,0,0
12.0,0,4,1,0,0,2,9,2,14,5,...,0,0,0,0,0,0,0,0,0,0
13.0,0,0,0,0,1,1,7,1,0,1,...,0,0,0,0,0,0,0,0,0,0
14.0,0,1,0,0,0,0,2,2,1,1,...,1,0,0,0,0,0,0,0,0,1
15.0,0,0,0,0,0,0,4,1,3,5,...,0,0,0,0,0,0,0,0,0,0
16.0,0,1,0,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,1
17.0,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
18.0,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
20.0,0,0,0,0,0,1,1,1,3,0,...,0,4,0,0,0,0,0,0,0,0
21.0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
22.0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
23.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24.0,0,0,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,0
25.0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
26.0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
31.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
33.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
35.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
37.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
127.0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
(null),4,576,465,195,68,10,2,1,0,0,...,0,0,0,0,0,0,0,0,0,1036

<font size="+1" color="blue">**Write your strategy for handling null values in bathrooms and bedrooms**. Justify briefly your choices.</font>

**Answer:** the strategy for handling missing values in `bathrooms`, `bathrooms_text`, `bedrooms` and `beds` will be as follows.

For columns `bathrooms` and `bathrooms_text`:
* (a) If `bathrooms` is not Null and `bathrooms_text` is Null and `bathrooms`==0.5, we fill `bathrooms_text` with "Half-bath". (b) If `bathrooms` is not Null and `bathrooms_text` is Null and `bathrooms`==1.0, we fill `bathrooms_text` with "1 bath". (c) If `bathrooms` is not Null and `bathrooms_text` is Null and `bathrooms`>1.0, we fill `bathrooms_text` with "{bathrooms} baths". (d) If `bathrooms_text` is not Null and `bathrooms` is Null
and `bathrooms_text` is in ["Half-bath", "Private half-bath", "Shared half-bath"], we fill `bathrooms` with 0.5, else we fill `bathrooms` with the float(N) in start of `bathrooms_text`. (e) If both `bathrooms_text` and `bathrooms` are Null, we fill them with the modal value of the original `bathrooms` columns, which is 1.0 and assign `bathrooms_text` as "1 bath".

For columns `bedrooms` and `beds`:
* (a) If `bedrooms` is not Null and `beds` is Null, we fill `beds` with `bedrooms` number. (b) If `beds` is not Null and `bedrooms` is Null and `beds`<2, we fill `bedrooms` with `beds`. (c) If `beds` is not Null and `bedrooms` is Null and `beds`>=2, we fill `bedrooms` with `beds`-1. (d) If both `beds` and `bedrooms` are Null, we fill them both with 1.0.

<font size="+1" color="blue">**Implement your strategy for handling null values in bathrooms and bedrooms**. </font>

In [13]:
def handle_null_values_bathrooms_bedrooms(df):
    df_clean = df.copy()
    
    # YOUR CODE HERE
    for index, row in df_clean.iterrows():
        # beds and bedrooms part
        if pd.isna(row['beds']) and pd.isna(row['bedrooms']):
            df_clean.at[index, "beds"] = 1
            df_clean.at[index, "bedrooms"] = 1
        elif pd.isna(row['beds']) and not pd.isna(row['bedrooms']):
            df_clean.at[index, "beds"] = row['bedrooms']
        elif not pd.isna(row['beds']) and pd.isna(row['bedrooms']):
            if row['beds'] >= 2:
                df_clean.at[index, "bedrooms"] = row['beds'] - 1
            else:
                df_clean.at[index, "bedrooms"] = row['beds']
                
        # bathrooms and bathrooms_text part
        if pd.isna(row['bathrooms']) and pd.isna(row['bathrooms_text']):
            df_clean.at[index, 'bathrooms'] = 1.0
            df_clean.at[index, 'bathrooms_text'] = "1 bath"
        elif not pd.isna(row['bathrooms']) and pd.isna(row['bathrooms_text']):
            if row['bathrooms']==0.5:
                df_clean.at[index, 'bathrooms_text'] = "Half-bath"
            elif row['bathrooms']==1:
                df_clean.at[index, 'bathrooms_text'] = "1 bath"
            else:
                if row['bathrooms']%1==0:
                    df_clean.at[index, 'bathrooms_text'] = f"{int(row['bathrooms'])} baths"
                else:
                    df_clean.at[index, 'bathrooms_text'] = f"{row['bathrooms']} baths"
                    
        elif pd.isna(row['bathrooms']) and not pd.isna(row['bathrooms_text']):
            if row['bathrooms_text'] in ["Half-bath", "Private half-bath", "Shared half-bath"]:
                df_clean.at[index, 'bathrooms'] = 0.5
            else:
                df_clean.at[index, 'bathrooms'] = float(row['bathrooms_text'].split()[0])
    return df_clean
    
df3 = handle_null_values_bathrooms_bedrooms(df2)

# This should show no NULL values in bathrooms or bedrooms
display(null_value_counts(df3))

                         column  null_count
0                   description         562
1                         price        1926
2      price_quote_checkin_date        1620
3     price_quote_checkout_date        1620
4       price_quote_total_price        1926
5   price_quote_price_per_night        1926
6               price_quote_raw        1620
7                minimum_nights           1
8                maximum_nights           1
9        minimum_minimum_nights           1
10       maximum_minimum_nights           1
11       minimum_maximum_nights           1
12       maximum_maximum_nights           1
13             has_availability          74
14      estimated_revenue_l365d        1926
15                 first_review        3523
16                  last_review        3523
17         review_scores_rating        3523
18       review_scores_accuracy        3524
19    review_scores_cleanliness        3524
20        review_scores_checkin        3524
21  review_scores_communication        3524
22       review_scores_location        3524
23          review_scores_value        3524
24                      license        2953
25            reviews_per_month        3523

# 6. Handle null values in other columns <font color="blue">[20%]</font>

<font size="+1" color="blue">**Write your strategy for the remaining columns with null values**. Indicate for each column if you will (a) drop the rows containig null values, (b) replace by a modal value, (c) replace by a zero or empty string. Justify briefly each choice.</font>

**Answer:** the strategy for handling missing values will be as follows.

Columns related to the description of the property:

* Column `description`: replace with an empty string, as an empty description is valid.

Columns related to minimum and maximum number of nights (`*_nights`): 

* Column `minimum_nights`, `maximum_nights`, `minimum_minimum_nights`, `maximum_minimum_nights`, `minimum_maximum_nights`, `maximum_maximum_nights`: drop, since they has very small amount of null data, dropping them won't have significant affect.

Columns related to availability, price, and license:

* Column `has_availability`, `price`, `price_quote_checkin_date`, `price_quote_checkout_date`, `price_quote_total_price`, `price_quote_price_per_night`, `price_quote_raw`, `license`: drop, since we cannot handle listings if we do not know if they are available, how much they cost, or if they are not licensed.

* Column `estimated_revenue_l365d`: will be automatically dropped out if we dropped the null values in `price`

Columns related to reviews:
* Column `review_scores_rating`, `review_scores_accuracy`, `review_scores_cleanliness`, `review_scores_checkin`, `review_scores_location`, `review_scores_value`, `review_scores_communication`: replace with average, since we do not want to penalize listings that have not received a review, so we will replace all scores in the reviews by their average values

* Column `reviews_per_month`: replace with 0, since without the `reviews_per_month` likely indicates there is not reviews yet

* Column `first_review` `last_review`: replace `first_review` and `last_review` with the smallest `first_review` and `last_review`, since without the dates likely indicates that there is no review, and making the `first_review` `last_review` far from current time is more logical

<font size="+1" color="blue">**Implement your strategy for handling the remaining null values**. </font>

In [14]:
def handle_remaining_null_values(df):
    df_clean = df.copy()
    
    # YOUR CODE HERE
    df_clean["description"] = df_clean["description"].fillna("")
    
    df_clean = df_clean.dropna(axis=0, subset=[
        'has_availability',
        'price',
        'license',
        'price_quote_checkin_date',
        'price_quote_checkout_date',
        'price_quote_total_price',
        'price_quote_price_per_night',
        'price_quote_raw']
                               )
    
    df_clean = df_clean.dropna(axis=0, subset=['minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights'])
    
    replace_with_average_columns = [
        'review_scores_rating',
        'review_scores_accuracy',
        'review_scores_cleanliness',
        'review_scores_checkin',
        'review_scores_location',
        'review_scores_value',
        'review_scores_communication'
        ]
    
    for column in replace_with_average_columns:
        df_clean[column] = df_clean[column].fillna(df_clean[column].mean())
        
    df_clean["reviews_per_month"] = df_clean["reviews_per_month"].fillna(0)
        
    df_clean["first_review"] = df_clean["first_review"].fillna(df_clean["first_review"].min())
    df_clean["last_review"] = df_clean["last_review"].fillna(df_clean["last_review"].min())
    
    return df_clean
    
df4 = handle_remaining_null_values(df3)

# This should show no column with a null value
display(null_value_counts(df4))

Empty DataFrame
Columns: [column, null_count]
Index: []

In [15]:
# LEAVE AS-IS

# Save the data, we will use it in the next assignment
df4.to_csv("listings_clean.csv.gz", index=False, compression="gzip")

<font size="+2" color="#003300">I hereby declare that I completed this practice myself, that I have not copied it from others, or from external sources without citing them, and that I have followed the generative AI instructions stated above.</font>